# Generated by Django 4.1.1 on 2022-10-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fkip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='alamat_rumah',
            new_name='NIDN',
        ),
        migrations.RenameField(
            model_name='dosen',
            old_name='fakultas',
            new_name='jabatan',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='prodi',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='tanggal_lahir',
        ),
    ]
